# Less Aggressive AI - build script
#
# Stamps src\WarMotives.txt into every AI faction event file of each target
# map.  Run this after editing src\WarMotives.txt, then start a NEW game.
#
#   powershell -ExecutionPolicy Bypass -File build.ps1
#
# Why copies?  The map's faction files reach shared code via USE, and USE'd
# files resolve to the base game, not to mods - so an override of the shared
# file is silently ignored.  Overrides of the faction files themselves DO load.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$src  = Get-Content (Join-Path $root 'src\WarMotives.txt') -Raw

# map folder (under Maps\) -> AI faction event files to generate
$maps = @{
  # Every AI-capable faction, Neutral included: any faction without the script
  # is unleashed vanilla AI and becomes the map's war outlet.
  'IronCurtain.virtual' = @(
    'United States', 'Soviet Union', 'NATO', 'Warsaw Pact',
    'American Allies', 'Soviet Allies', 'China', 'India', 'Pakistan', 'Neutral'
  )
}

$footer = @"


// ------------------------------------------------ faction entry point --
// (generated by build.ps1 - edit src\WarMotives.txt, not this file)

FOR AI
  SetWarMotives()

FOR BOTH

END
"@

# --- optional stricter garrison (OFF by default: vanilla build logic) -------
# With the motive layer gating the DECISION to go to war, the extra garrison
# requirement is just delay on top.  Set $StricterGarrison = $true to inline
# src\StaticDefence.txt into AI\StrategyConquest.txt again.
$StricterGarrison = $false
$gameRoot = Split-Path -Parent (Split-Path -Parent $root)
$strategyOut = Join-Path $root 'AI\StrategyConquest.txt'
if ($StricterGarrison) {
  # --- AI/StrategyConquest.txt: vanilla file with our DefenseGroups inlined ---
  # The engine opens AI/StrategyConquest.txt directly, but the strategies pull
  # StaticDefence.txt in via USE (base game only), so the garrison rules must be
  # pasted into each strategy here.
  $vanilla  = Get-Content (Join-Path $gameRoot 'AI\StrategyConquest.txt') -Raw
  $garrison = Get-Content (Join-Path $root 'src\StaticDefence.txt') -Raw
  $block    = $garrison.Substring($garrison.IndexOf('  DefenseGroups')).TrimEnd() + "`n"
  $inline   = "  // --- inlined from src\StaticDefence.txt (USE'd files resolve to the base game) ---`n" + $block + "`n"
  $strategy = $vanilla -replace '(?m)^  USE "AI/Default/StaticDefence\.txt"\r?\n', $inline
  $nInlined = ([regex]::Matches($strategy, '(?m)^  DefenseGroups\s*$')).Count
  if ($nInlined -ne 3) { throw "expected 3 inlined DefenseGroups blocks, got $nInlined" }
  $hdr = "// Less Aggressive AI - overrides AI/StrategyConquest.txt (loaded directly by the engine).`n// Generated by build.ps1: vanilla file with each strategy's DefenseGroups block replaced`n// by the mod's mandatory-garrison version from src\StaticDefence.txt.`n`n"
  New-Item -ItemType Directory -Force (Join-Path $root 'AI') | Out-Null
  [IO.File]::WriteAllText((Join-Path $root 'AI\StrategyConquest.txt'), ($hdr + $strategy), (New-Object Text.UTF8Encoding($false)))
  Write-Host "Generated AI\StrategyConquest.txt ($nInlined strategies)."
} else {
  Remove-Item $strategyOut -ErrorAction SilentlyContinue
  Write-Host "AI\StrategyConquest.txt not generated (vanilla garrison)."
}

$count = 0
foreach ($map in $maps.Keys) {
  # the map's DefaultEnemy pairs -> per-faction MAP_RIVALS set (the "old
  # rivalry" motive; GET_ENEMIES only reports actual wars)
  $mapTxt   = Get-Content (Join-Path $gameRoot ("Maps\" + ($map -replace '\.virtual$', '.txt'))) -Raw
  $rivalsOf = @{}
  foreach ($m in [regex]::Matches($mapTxt, '(?m)^\s*DefaultEnemy\s+"([^"]+)"\s+"([^"]+)"')) {
    if (-not $rivalsOf.ContainsKey($m.Groups[1].Value)) { $rivalsOf[$m.Groups[1].Value] = @() }
    $rivalsOf[$m.Groups[1].Value] += $m.Groups[2].Value
  }

  $dir = Join-Path $root "Maps\$map\Events"
  New-Item -ItemType Directory -Force $dir | Out-Null
  foreach ($faction in $maps[$map]) {
    $list = @('""')
    if ($rivalsOf.ContainsKey($faction)) { $list = $rivalsOf[$faction] | ForEach-Object { '"' + $_ + '"' } }
    $stamp = "// generated by build.ps1 for faction `"$faction`" - edit src\WarMotives.txt, not this file`n" +
             "def set MAP_RIVALS = {" + ($list -join ', ') + "}`n" +
             "def set ALL_FACTIONS = {" + (($maps[$map] | ForEach-Object { '"' + $_ + '"' }) -join ', ') + "}`n`n"
    # attack hooks with literal names (one per other faction)
    $hooks = ($maps[$map] | Where-Object { $_ -ne $faction } | ForEach-Object {
      "  ON Attacked anything ATTACKER `"$_`" OnAttackedBy(`"$_`")" }) -join "`n"
    $body  = $footer -replace '  SetWarMotives\(\)', ("  SetWarMotives()`n`n  // release the leash on anyone who attacks us`n" + $hooks)
    $path = Join-Path $dir "$faction.txt"
    [IO.File]::WriteAllText($path, ($stamp + $src.TrimEnd() + $body), (New-Object Text.UTF8Encoding($false)))
    $count++
  }
}
Write-Host "Generated $count faction event files."
