# Less Aggressive AI - build script
#
# Stamps src\WarMotives.txt into every AI faction event file of each target
# map.  Run this after editing src\WarMotives.txt, then start a NEW game.
#
#   powershell -ExecutionPolicy Bypass -File build.ps1
#
# Why copies?  The map's faction files reach shared code via USE, and USE'd
# files resolve to the base game, not to mods - so an override of the shared
# file is silently ignored.  Overrides of the faction files themselves DO load.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$src  = Get-Content (Join-Path $root 'src\WarMotives.txt') -Raw

# map folder (under Maps\) -> AI faction event files to generate
$maps = @{
  # Every AI-capable faction, Neutral included: any faction without the script
  # is unleashed vanilla AI and becomes the map's war outlet.
  'IronCurtain.virtual' = @(
    'United States', 'Soviet Union', 'NATO', 'Warsaw Pact',
    'American Allies', 'Soviet Allies', 'China', 'India', 'Pakistan', 'Neutral'
  )
}

$footer = @"


// ------------------------------------------------ faction entry point --
// (generated by build.ps1 - edit src\WarMotives.txt, not this file)

FOR AI
  SetWarMotives()

FOR BOTH

END
"@

# --- optional stricter garrison (OFF by default: vanilla build logic) -------
# With the motive layer gating the DECISION to go to war, the extra garrison
# requirement is just delay on top.  Set $StricterGarrison = $true to inline
# src\StaticDefence.txt into AI\StrategyConquest.txt again.
$StricterGarrison = $false
$gameRoot = Split-Path -Parent (Split-Path -Parent $root)
$strategyOut = Join-Path $root 'AI\StrategyConquest.txt'
if ($StricterGarrison) {
  # --- AI/StrategyConquest.txt: vanilla file with our DefenseGroups inlined ---
  # The engine opens AI/StrategyConquest.txt directly, but the strategies pull
  # StaticDefence.txt in via USE (base game only), so the garrison rules must be
  # pasted into each strategy here.
  $vanilla  = Get-Content (Join-Path $gameRoot 'AI\StrategyConquest.txt') -Raw
  $garrison = Get-Content (Join-Path $root 'src\StaticDefence.txt') -Raw
  $block    = $garrison.Substring($garrison.IndexOf('  DefenseGroups')).TrimEnd() + "`n"
  $inline   = "  // --- inlined from src\StaticDefence.txt (USE'd files resolve to the base game) ---`n" + $block + "`n"
  $strategy = $vanilla -replace '(?m)^  USE "AI/Default/StaticDefence\.txt"\r?\n', $inline
  $nInlined = ([regex]::Matches($strategy, '(?m)^  DefenseGroups\s*$')).Count
  if ($nInlined -ne 3) { throw "expected 3 inlined DefenseGroups blocks, got $nInlined" }
  $hdr = "// Less Aggressive AI - overrides AI/StrategyConquest.txt (loaded directly by the engine).`n// Generated by build.ps1: vanilla file with each strategy's DefenseGroups block replaced`n// by the mod's mandatory-garrison version from src\StaticDefence.txt.`n`n"
  New-Item -ItemType Directory -Force (Join-Path $root 'AI') | Out-Null
  [IO.File]::WriteAllText((Join-Path $root 'AI\StrategyConquest.txt'), ($hdr + $strategy), (New-Object Text.UTF8Encoding($false)))
  Write-Host "Generated AI\StrategyConquest.txt ($nInlined strategies)."
} else {
  Remove-Item $strategyOut -ErrorAction SilentlyContinue
  Write-Host "AI\StrategyConquest.txt not generated (vanilla garrison)."
}

# --- optional colourblind-friendly faction palette (OFF by default) -------
# Overrides the Color of each Player in the map file (opened directly by the
# engine).  Built for a weak red cone (protan): factions are separated by
# LIGHTNESS and the blue-yellow axis, no purples, reds kept light.
$ColorblindPalette = $false
$palette = @{
  'United States'='00A0FF'; 'Soviet Union'='FF6040'; 'NATO'='FFFFFF'; 'Warsaw Pact'='3A1E00'
  'American Allies'='00E0A0'; 'Soviet Allies'='8B0000'; 'China'='FFE000'; 'India'='FFB000'
  'Pakistan'='3C5A14'; 'Neutral'='909090'
}
foreach ($map in $maps.Keys) {
  $mapFile = ($map -replace '\.virtual$', '.txt')
  $out = Join-Path $root "Maps\$mapFile"
  if ($ColorblindPalette) {
    $txt = Get-Content (Join-Path $gameRoot "Maps\$mapFile") -Raw
    foreach ($f in $palette.Keys) {
      $txt = $txt -replace ('(?m)^(\s*Player "' + [regex]::Escape($f) + '" Color ")[0-9A-Fa-f]+(")'), ('${1}' + $palette[$f] + '${2}')
    }
    [IO.File]::WriteAllText($out, $txt, (New-Object Text.UTF8Encoding($false)))
    Write-Host "Generated Maps\$mapFile with the colourblind palette."
  } else {
    Remove-Item $out -ErrorAction SilentlyContinue
  }
}

# --- sanity check the script before stamping it anywhere -------------------
# every block called must exist and be defined ABOVE its first use (the parser
# only knows blocks it has already read), and control flow must balance
$defs = @{}
$srcLines = $src -split "`r?`n"
for ($i = 0; $i -lt $srcLines.Count; $i++) {
  if ($srcLines[$i] -cmatch '^BLOCK (?:int )?(\w+)\(') { if (-not $defs.ContainsKey($Matches[1])) { $defs[$Matches[1]] = $i } }
}
# language keywords, operators and engine functions that are not our blocks
$builtin = @('if','while','ForEach','not','AND','OR','def','return','break',
  'SIZE_OF','GET_ELEMENT','RAND','MIN','MAX','LERP','DISTANCE','SELECT',
  'REGION_OWNER','REGION_ID','REGION_NAME','REGION_ORIGINAL_OWNER','REGION_CITIES',
  'FACTION_ID','FACTION_NAME','FACTION_REGIONS','FACTION_SCORE','GET_FACTIONS',
  'GET_ENEMIES','GET_ALLIES','GET_PERMANENT_ALLIES','GET_RELATIONS','PERMANENT_ALLIES',
  'ENEMIES','ENEMY','ALLIES','ADJACENT_REGIONS','STAT','MINUTES','SECONDS','HOURS',
  'VISIBLE_FOR','PRINCIPAL_TYPE','OWNER','CLASS','TERRITORY','REGION','CURRENT_TICK',
  'SET_NAME','ID_NAME','CREATE_UNIT','MAKE_GROUP','HEALTH','POSITION','GET_BIT')
$problems = @()
for ($i = 0; $i -lt $srcLines.Count; $i++) {
  $line = $srcLines[$i]
  $line = [regex]::Replace($line, '"[^"]*"', '""')   # blank out string literals
  $line = [regex]::Replace($line, '//.*$', '')       # and trailing comments
  if ($line -match '^\s*$') { continue }
  foreach ($m in [regex]::Matches($line, '\b([A-Za-z_]\w*)\s*\(')) {
    $name = $m.Groups[1].Value
    if ($builtin -contains $name) { continue }
    if ($line -cmatch ('^BLOCK (?:int )?' + [regex]::Escape($name) + '\(')) { continue }
    if (-not $defs.ContainsKey($name)) { $problems += "line $($i+1): calls '$name' which is not defined"; continue }
    if ($defs[$name] -gt $i) { $problems += "line $($i+1): calls '$name', defined later at line $($defs[$name]+1)" }
  }
}
$opens = ($srcLines | Where-Object { $_ -cmatch '^\s*(if|while|ForEach)\b' }).Count
$ends  = ($srcLines | Where-Object { $_ -cmatch '^\s*end(\s*//.*)?\s*$' }).Count
if ($opens -ne $ends) { $problems += "control flow unbalanced: $opens openers vs $ends 'end' lines" }
$nb = ($srcLines | Where-Object { $_ -cmatch '^BLOCK ' }).Count
$ne = ($srcLines | Where-Object { $_ -cmatch '^END\s*$' }).Count
if ($nb -ne $ne) { $problems += "BLOCK/END unbalanced: $nb vs $ne" }
if ($problems.Count) {
  Write-Host "src\WarMotives.txt has problems:" -ForegroundColor Red
  $problems | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
  throw "refusing to build"
}
Write-Host "src\WarMotives.txt checks out ($($defs.Count) blocks, $opens/$ends control, $nb/$ne blocks)."

$count = 0
foreach ($map in $maps.Keys) {
  # the map's DefaultEnemy pairs -> per-faction MAP_RIVALS set (the "old
  # rivalry" motive; GET_ENEMIES only reports actual wars)
  $mapTxt   = Get-Content (Join-Path $gameRoot ("Maps\" + ($map -replace '\.virtual$', '.txt'))) -Raw
  $rivalsOf = @{}
  foreach ($m in [regex]::Matches($mapTxt, '(?m)^\s*DefaultEnemy\s+"([^"]+)"\s+"([^"]+)"')) {
    if (-not $rivalsOf.ContainsKey($m.Groups[1].Value)) { $rivalsOf[$m.Groups[1].Value] = @() }
    $rivalsOf[$m.Groups[1].Value] += $m.Groups[2].Value
  }

  $dir = Join-Path $root "Maps\$map\Events"
  New-Item -ItemType Directory -Force $dir | Out-Null
  foreach ($faction in $maps[$map]) {
    $list = @('""')
    if ($rivalsOf.ContainsKey($faction)) { $list = $rivalsOf[$faction] | ForEach-Object { '"' + $_ + '"' } }
    $stamp = "// generated by build.ps1 for faction `"$faction`" - edit src\WarMotives.txt, not this file`n" +
             "def set MAP_RIVALS = {" + ($list -join ', ') + "}`n" +
             "def set ALL_FACTIONS = {" + (($maps[$map] | ForEach-Object { '"' + $_ + '"' }) -join ', ') + "}`n" +
             "def int EVAL_OFFSET_SEC = " + (40 * [array]::IndexOf($maps[$map], $faction)) + "  // staggers evaluations across factions`n`n"
    # attack hooks with literal names (one per other faction)
    # a shot that destroys nothing is an incident (grievance); losing a unit
    # or having territory invaded is an attack (immediate retaliation)
    $hooks = ($maps[$map] | Where-Object { $_ -ne $faction } | ForEach-Object {
      "  ON Attacked anything ATTACKER `"$_`" OnIncidentBy(`"$_`")`n" +
      "  ON Destroyed anything ATTACKER `"$_`" OnAttackedBy(`"$_`")`n" +
      "  ON Region_Invaded ANY OF ME BY `"$_`" OnAttackedBy(`"$_`")" }) -join "`n"
    $body  = $footer -replace '  SetWarMotives\(\)', ("  SetWarMotives()`n`n  // release the leash on anyone who attacks us`n" + $hooks)
    $path = Join-Path $dir "$faction.txt"
    [IO.File]::WriteAllText($path, ($stamp + $src.TrimEnd() + $body), (New-Object Text.UTF8Encoding($false)))
    $count++
  }
}
Write-Host "Generated $count faction event files."
